<<<<<<< HEAD
--- ERROR | 2024-07-31 18:21:29,255 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
--- ERROR | 2024-07-31 15:02:45,651 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 18:21:29,262 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 15:02:45,702 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 18:24:12,817 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 13:19:34,088 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 117, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 18:24:12,826 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 13:19:34,129 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 117, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 18:25:36,638 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 13:41:29,333 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 117, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 18:25:36,650 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 13:41:29,343 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 117, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 18:33:16,358 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 13:41:55,157 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 117, in validate_token
    # В данном примере мы просто проверяем, что в токене есть поле 'sub'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 18:33:21,986 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 117, in validate_token
    # В данном примере мы просто проверяем, что в токене есть поле 'sub'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 18:33:22,002 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 117, in validate_token
    # В данном примере мы просто проверяем, что в токене есть поле 'sub'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 18:45:33,838 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 18:45:33,849 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 13:44:05,419 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 18:50:54,439 | Токен недействительный-  | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 13:44:05,434 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 18:50:54,458 | Токен недействительный-  | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 13:44:43,518 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 18:53:49,433 | Токен недействительный-  | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 13:46:34,316 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 18:53:51,164 | Токен недействительный-  | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 13:46:34,326 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 18:53:51,176 | Токен недействительный-  | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 13:50:03,081 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 19:00:03,369 | Токен недействительный-  | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 13:50:03,095 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 19:02:54,853 | Токен недействительный-  | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 13:50:25,855 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 19:02:54,868 | Токен недействительный-  | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 13:50:25,866 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 19:06:22,118 | Токен недействительный-  | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 13:52:41,307 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 19:36:24,034 | Токен недействительный-  | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 14:16:17,106 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 19:36:24,039 | Токен недействительный-  | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 14:16:17,118 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 20:15:03,039 | Токен недействительный-  | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 14:17:40,121 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-07-31 20:15:03,059 | Токен недействительный-  | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 14:17:40,130 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
>>>>>>> 27e3c87 (bakend files)
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
=======
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
>>>>>>> 27e3c87 (bakend files)
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<<<<<<< HEAD
  File "C:\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scheduling-app\backend\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
=======
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 14:25:48,387 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 14:25:54,791 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 14:25:54,808 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 14:29:40,432 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 14:29:40,444 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 14:36:45,940 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 14:36:45,952 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 14:37:57,537 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 14:37:57,547 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 15:59:44,635 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 157, in decode
    _validate_claims(
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 481, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 314, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.
--- ERROR | 2024-08-02 19:59:11,683 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 19:59:11,724 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 20:00:46,311 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 20:00:46,331 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-02 20:01:18,934 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 70, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jws.py", line 180, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 144, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
--- ERROR | 2024-08-07 15:43:23,309 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 157, in decode
    _validate_claims(
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 481, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 314, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.
--- ERROR | 2024-08-07 15:43:23,333 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 157, in decode
    _validate_claims(
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 481, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 314, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.
--- ERROR | 2024-08-07 15:43:49,023 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 157, in decode
    _validate_claims(
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 481, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 314, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.
--- ERROR | 2024-08-07 15:43:49,030 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 157, in decode
    _validate_claims(
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 481, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 314, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.
--- ERROR | 2024-08-07 18:28:26,276 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 157, in decode
    _validate_claims(
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 481, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 314, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.
--- ERROR | 2024-08-07 18:28:28,837 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 157, in decode
    _validate_claims(
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 481, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 314, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.
--- ERROR | 2024-08-07 18:28:28,847 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 157, in decode
    _validate_claims(
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 481, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 314, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.
--- ERROR | 2024-08-07 21:08:38,342 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 157, in decode
    _validate_claims(
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 481, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 314, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.
--- ERROR | 2024-08-07 21:08:38,359 | Токен недействительный | Filename:authentication.py Func:def validate_token
Traceback (most recent call last):
  File "c:\Users\Etein\Documents\GitHub\scheduling-app\backend\api_fast_api\auth\authentication.py", line 116, in validate_token
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 157, in decode
    _validate_claims(
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 481, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "C:\Users\Etein\Documents\GitHub\scheduling-app\.venv\Lib\site-packages\jose\jwt.py", line 314, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.
--- ERROR | 2024-08-17 16:39:45,804 | error - Incorrect date format: time data '2025-13-1' does not match format '%Y-%m-%d' | Filename:async_models.py Func:def async_lesson_dates_for_the_month_db_frontend

--- ERROR | 2024-08-17 16:39:48,032 | error - Incorrect date format: time data '2024-0-1' does not match format '%Y-%m-%d' | Filename:async_models.py Func:def async_lesson_dates_for_the_month_db_frontend

>>>>>>> 27e3c87 (bakend files)
